sudo: required
dist: trusty
language: cpp

env:
  - QT_BASE=55
  - QT_BASE=56

before_install:
  - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install xvfb
  - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh; fi
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi

script:
  - mkdir build
  - cd build
  - qmake .. && make
  - xvfb-run -a -s "-screen 0 800x600x24" tests/test

notifications:
  email: false