sudo: required
dist: trusty
language: cpp

env:
  - QT_BASE=53
  - QT_BASE=55
  - QT_BASE=56
  - QT_BASE=57
  - QT_BASE=58
  - QT_BASE=xenial
  - QT_BASE=yakkety
  - QT_BASE=zesty
  - QT_BASE=appimage
  - QT_BASE=snap

service:
  - docker

before_install:
  - git fetch --unshallow
  - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y; fi
  - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
  - if [ "$QT_BASE" = "xenial" ]; then docker pull theshadowx/qt5:default_qt5_xenial; fi
  - if [ "$QT_BASE" = "yakkety" ]; then docker pull theshadowx/qt5:default_qt5_yakkety; fi
  - if [ "$QT_BASE" = "zesty" ]; then docker pull theshadowx/qt5:default_qt5_zesty; fi
  - if [ "$QT_BASE" = "appimage" ]; then docker pull theshadowx/docker-snapcraft-qt:qt55; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install software-properties-common checkinstall xvfb dh-make fakeroot gpgv2 tree
  - if [ "$QT_BASE" == "53" ]; then sudo apt-get install -qq qt53base; source /opt/qt53/bin/qt53-env.sh; fi
  - if [ "$QT_BASE" == "55" ]; then sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh; fi
  - if [ "$QT_BASE" == "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" == "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi
  - if [ "$QT_BASE" == "58" ]; then sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh; fi

before_script:
    - echo "$QT_BASE:$TRAVIS_BRANCH----------------------------------------------------------------------------------------------"
    - if [ "$QT_BASE" == "53" ]; then qmake -v; fi
    - if [ "$QT_BASE" == "55" ]; then qmake -v; fi
    - if [ "$QT_BASE" == "56" ]; then qmake -v; fi
    - if [ "$QT_BASE" == "57" ]; then qmake -v; fi
    - if [ "$QT_BASE" == "58" ]; then qmake -v; fi
    - if [ "$QT_BASE" == "xenial" ]; then docker run --rm -it theshadowx/qt5:default_qt5_xenial qmake -v; fi
    - if [ "$QT_BASE" == "yakkety" ]; then docker run --rm -it theshadowx/qt5:default_qt5_yakkety qmake -v; fi
    - if [ "$QT_BASE" == "zesty" ]; then docker run --rm -it theshadowx/qt5:default_qt5_zesty qmake -v; fi
    - mkdir build;
    - cd build;

script:
    - if [ "$QT_BASE" == "xenial" ]; then
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_xenial qmake ../src/;
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_xenial make deb;
      elif [ "$QT_BASE" == "yakkety" ]; then
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_yakkety qmake ../src/;
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_yakkety make deb;
      elif [ "$QT_BASE" == "zesty" ]; then
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_zesty qmake ../src/;
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_zesty make deb;
      elif [ "$QT_BASE" == "snap" ]; then
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_xenial qmake ../src/;
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_xenial make snap;
      elif [ "$QT_BASE" == "appimage" ]; then
        docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_xenial qmake ../src/;
        docker run --rm -it --privileged -v ${TRAVIS_BUILD_DIR}:/home/root/notes -w=/home/root/notes/build theshadowx/qt5:default_qt5_xenial make appimage;
      else
        qmake ../src;
        make -j4;
        echo "-----------------------------------------------";
        make deb;
      fi

after_success:

  - if [[ "$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
        export NOTES_VERSION=$(git describe --always --tags HEAD | cut -d- -f1 | sed 's/^v//')-git$(git rev-parse --short HEAD)
    else
        export NOTES_VERSION=$(git describe --always --tags HEAD | cut -d- -f1 | sed 's/^v//')
    fi

    if [[ "$QT_BASE" == "xenial" || "$QT_BASE" == "yakkety" || "$QT_BASE" == "zesty" ]]; then
        mv deb/notes*.deb deb/notes_${NOTES_VERSION}_amd64-${QT_BASE}.deb
        curl --upload-file deb/notes*.deb https://transfer.sh/notes_${NOTES_VERSION}_amd64-${QT_BASE}.deb
    elif [ "$QT_BASE" == "appimage" ]; then
        mv Notes-*.AppImage notes_${NOTES_VERSION}_amd64.AppImage
        curl --upload-file ./notes_*.AppImage https://transfer.sh/notes_${NOTES_VERSION}_amd64.AppImage
    elif [ "$QT_BASE" == "snap" ]; then
        mv snap/notes*.snap snap/notes_${NOTES_VERSION}_amd64.snap
        curl --upload-file snap/notes*.snap https://transfer.sh/notes_${NOTES_VERSION}_amd64.snap
    fi

notifications:
  email: false

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  tag_name: "$TRAVIS_TAG"
  api_key:
    secure: YLGygfObrwNXKwdJTRVSsmKHoxDThRI7vsnOzlu442HiZcoA+iJXpxEEGFJj2RVeig4//cgZG3nymf/TmSRy3N3AH8o94AC/47glnGx5/z5/dxyNfe9mJol1v5DgadK92wN3HM9wi6ZL+TW8ecEzF4TKteS6JklxUWWVEnq544KnfQdmqUqRkrmJdBHo2OdVpbeJeKH3siWVHHXlfCaW+dlzGb2YwOkcCORcNImzcLjvd36ozMeA4DlH2TbWJysp2i5XxcjuRK9gnwOcNKm2tImTk82z3rwwQ2dy4bTzq1ryigHW0at4/jUzRBrKll5IQ6byY/9DtpRosgKGRKgaqssuxNiOvDzJ0M7qHPhoODMPXKueTChazY3FvrRuJ9sQndhGkreli9JpxCpcTLNOxD1kFgQlrFqmbmZWVHSEjYWXkPtEr1/rbyXFHhV6zfnhxkT24VC4w4wddYsd5zYuvwfYYIRyv5ISYddceIRXJDtli2xgBjlZnuLxU9UmqSwg8m6ETRee3Z6B6k7ojxrK5bOnnVbDHlHpbNmDMacZnyrZWibRgAhcRfaWZBDUYy45vxWjQVD4Z6UPc8XjJo/+axvqnICn2aqTKSguzQBnry5qOvF8n3QptL1yqhlsvLhRg3e17g1U6faS9+k09C/HHSdVBtNR3tWt+jGyxBGQ248=
  file:
    - Notes-*.AppImage
    - deb/notes*.deb
    - snap/notes*.snap
  file_glob: true
  on:
    repo: nuttyartist/notes
    tags: true
