sudo: required
dist: trusty
language: cpp

env:
  - QT_BASE=56
  - QT_BASE=57
  - QT_BASE=58

before_install:
  - sudo apt-get install software-properties-common
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install xvfb
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi
  - if [ "$QT_BASE" = "58" ]; then sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh; fi

script:
  - mkdir build
  - cd build
  - qmake PREFIX=/usr .. && make
  - xvfb-run -a -s "-screen 0 800x600x24" tests/test
  - sudo apt-get -y install checkinstall
  - sudo checkinstall --pkgname=app --pkgversion="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - cp ../../packaging/linux/common/notes.desktop .
  - cp ../../packaging/linux/common/icons/256x256/notes.png .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage 
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/notes -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/notes -appimage 
  - curl --upload-file ./Notes-*.AppImage https://transfer.sh/notes-git$(git rev-parse --short HEAD).qt$QT_BASE-x86_64.AppImage 
  
notifications:
  email: false
