name: notes
# Note on version: $UPSTREAM_VERSION~.git$GIT_COMMIT_ID
version: 0.9.0
summary: Note taking application, write down your thoughts.
description: |
  Notes is a tool for the things you need to write down off your
  brain. It is your place of expressing yourself. Notes is an open
  source and cross-platform project, and you're welcome to be part
  of it and contribute. We hope you will love it as much as we do.
confinement: strict

apps:
  notes:
    command: qt5-launch Notes
    plugs: [unity7, opengl, network-bind]

parts:
  notes:
    plugin: qmake
    source: ../../../src
    build-packages:
      - qtbase5-dev
      - qtbase5-dev-tools
      - qt5-qmake
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5core5a
      - libqt5libqgtk2
      - libglib2.0-0
      - libgtk2.0-bin
      - libgtk2.0-common
      - overlay-scrollbar-gtk2
      - unity-gtk2-module
      - libcanberra-gtk-module
      - libatk-adaptor
      - libgail-common
    after: [qt5conf-with-gtk]
