name: notes
# Note on version: $UPSTREAM_VERSION~.git$GIT_COMMIT_ID
summary: Note taking application, write down your thoughts.
description: |
  Notes is a tool for the things you need to write down off your
  brain. It is your place of expressing yourself. Notes is an open
  source and cross-platform project, and you're welcome to be part
  of it and contribute. We hope you will love it as much as we do.
version: latest
version-script: echo "$(git describe --tags | cut -c 2-)"

base: core18

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  notes:
    command: desktop-launch ${SNAP}/usr/bin/notes
#   desktop: usr/share/applications/notes.desktop
    plugs: [home, opengl, unity7, network]

parts:
  notes:
    plugin: qmake
    qt-version: qt5
    options:
      - PREFIX=/usr
      - CONFIG+=release
    source: .
    project-files: [src/Notes.pro]
    build-packages:
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtbase5-private-dev
      - qt5-qmake
    stage-packages:
      - fonts-liberation
      - libqt5gui5
      - libqt5widgets5
      - libqt5core5a
      - libqt5sql5
      - libqt5sql5-sqlite
    after: [desktop-qt5]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - libqt5gui5
      - try: [appmenu-qt5] # not available on core18
      - locales-all
